patches: amlogic: 6.7: openvfd driver: `disabled`
Need to fix:
drivers/auxdisplay/openvfd/openvfd_drv.c:43:7: warning: "CONFIG_AMLOGIC_LEGACY_EARLY_SUSPEND" is not defined, evaluates to 0 [-Wundef]
   43 | #elif CONFIG_AMLOGIC_LEGACY_EARLY_SUSPEND
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/auxdisplay/openvfd/openvfd_drv.c: In function ‘get_chip_pin_number’:
drivers/auxdisplay/openvfd/openvfd_drv.c:635:24: error: implicit declaration of function ‘gpiochip_find’; did you mean ‘gpiochip_add’? [-Werror=implicit-function-declaration]
  635 |                 chip = gpiochip_find((char *)bank_name, is_right_chip);
      |                        ^~~~~~~~~~~~~
      |                        gpiochip_add
drivers/auxdisplay/openvfd/openvfd_drv.c:635:22: warning: assignment to ‘struct gpio_chip *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  635 |                 chip = gpiochip_find((char *)bank_name, is_right_chip);
      |                      ^
cc1: some warnings being treated as errors

Signed-off-by: Patrick Yavitz <pyavitz@xxxxx.com>